server:
  port: 8082  # Choose a unique port

spring:
  application:
    name: property-service
  datasource:
    url: jdbc:mysql://localhost:3307/realestate
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
