server:
  port: 8081  # Choose a port

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/realestate
    username: root
    password: root  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
