server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: property-service
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/properties/**
